dataset:
  test_split_key: test
  train_split_key: train
  val_split_key: dev
eval:
#    checkpoint_path:
    postprocessing:
        output_type: classification
        transforms:
            -   CustomTransform:
                    transform: custom.segmentation_to_classification.SegmentationToClassification
                    params:
                        highest_pixel_count: 1
loss:
  CategoricalCrossEntropy:
    from_logits: false
    weights:
      - 0.6931471805599453
      - 6.641817714773443
      - 4.416118221840174
      - 6.7922406829099105
      - 5.619616994487083
metrics:
  - MeanIOU:
      from_logits: false
      ignore_zero: true
      name: mean_iou
      num_classes: 5
model:
  avi:
    Unet:
      activation: softmax
      backbone_name: resnet34
      decoder_block_type: transpose
      encoder_weights: imagenet
      input_shape:
        - null
        - null
        - null
      output_depth: 5
      tiling_config:
        perform_tiling: false
        stride: 512
        target_image_shape:
          - 512
          - 512
        tile_size: 512
monitor_metric:
  val_mean_iou: max
train:
  auto_tiling:
    information_based_sampling: true
    patch_sample_ratio: 0.8
    stride: 512
    tile_size: 512
    tiles_batch_size: 32
  auto_tuning:
    class_weights: true
    class_weights_method: 2
    debug: false
  batch_size: 0
  early_stop:
    metric: val_loss
    min_delta: 0
    min_epochs: 200
  epochs: 2000
  learning_rate: 0.0001
  validation_run_freq: 1